name = "jelly pack"
author = "dj enby"
version = "1.21.1-1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fee731e9e78025b8904272e195e1ac8cf9038de1bb3a75fb1d338bce08c73033"

[versions]
minecraft = "1.21.1"
quilt = "0.26.4-beta.5"

[options]
acceptable-game-versions = ["1.21"]
