name = "Jelly Pack"
author = "enby"
version = "1.20.2-0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e78eb2cc786c8fcf6205c3f59e377f5518ab582a984d91a03d0bb0eef73dad00"

[versions]
minecraft = "1.20.2"
quilt = "0.21.2"

[options]
acceptable-game-versions = ["1.19.4", "1.20", "1.20.1"]
