name = "Jelly Pack"
author = "enby"
version = "1.20.2-0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7820fa44767e86896356cc304b624aa81300cc14d95e7de56dcf0914b2ad2a64"

[versions]
minecraft = "1.20.2"
quilt = "0.21.2"

[options]
acceptable-game-versions = ["1.19.4", "1.20", "1.20.1"]
