name = "Jelly Pack"
author = "enby"
version = "1.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c37776e7c96f8d844e6836d11a3904bfa8e59095c7adb5621c7e124de58507ee"

[versions]
minecraft = "1.19.2"
quilt = "0.17.2-beta.2"

[options]
acceptable-game-versions = ["1.19", "1.19.1"]
