name = "Jelly Pack"
author = "enby"
version = "1.20.1-1.7.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "53d46ed7616c308a94375d32c594f29a771f02401d22eee96058f9a75b06454b"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2", "1.19.3", "1.19.4", "1.20"]
