name = "jelly pack"
author = "dj enby"
version = "1.21.5-0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ff2e82b9cc5413b7ba446ae7f3d90deccff443d0ab199d6d48e46c60cd7ffa0e"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"

[options]
acceptable-game-versions = ["1.21", "1.21.1", "1.21.2", "1.21.3", "1.21.4"]
