name = "jelly pack"
author = "dj enby"
version = "1.21.5-0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b43605cf404f347cec2090ac26cd09ffa2ad7538156694126e85ce648022fd56"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"

[options]
acceptable-game-versions = ["1.21", "1.21.1", "1.21.2", "1.21.3", "1.21.4"]
