name = "Jelly Pack"
author = "dj enby"
version = "1.21.5-0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b35a4f625e3724629d1f009b998d54f69b7d57743a50262918bad3b601cfc979"

[versions]
minecraft = "1.21.5"
quilt = "0.29.0-beta.5"

[options]
acceptable-game-versions = ["1.21", "1.21.1", "1.21.2", "1.21.3", "1.21.4"]
