name = "Jelly Pack"
author = "enby"
version = "1.19.4-1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c60ca784437aa3e95a49cdb6dcdd6b8b4db37d1ffcfa658cc5eb9b39056171c"

[versions]
minecraft = "1.19.4"
quilt = "0.18.10"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2", "1.19.3"]
